<a href="https://colab.research.google.com/github/Tejaswimadastu/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [ ]:
import numpy as np
arr=np.array(42)
print(arr.ndim)
arr1=np.array([4,5,6])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
arr3=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

0
[4 5 6]
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [ ]:
zeroes=np.zeros((4,3))
print(zeroes)
ones=np.ones((4,5))
print(ones)
rand=np.random.random((2,3))
print(rand)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.16379574 0.69376225 0.88936777]
 [0.96989569 0.38393626 0.60228643]]


In [ ]:
iden=np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
steps=np.arange(2,10,2)
print(steps)

[2 4 6 8]


# Data Engineer

In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Shape ",temp_data.shape)
print("Size ",temp_data.size)
print("Data_type ",temp_data.dtype)
print("Number of dimensions ",temp_data.ndim)
gh3=np.array([21,23,22])
updated_temp_data=np.vstack((temp_data,gh3))
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)
greenhouse_identity=np.eye(3,3)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]
Shape  (2, 3)
Size  6
Data_type  int64
Number of dimensions  2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Indexing & Slicing

In [ ]:
array=np.array([[1,2,3],[4,5,6]])
print(array[0][1])
print(array[1][-2])
print(array[::-1])
print(array[1][::-1])

2
5
[[4 5 6]
 [1 2 3]]
[6 5 4]


# Data Analyst

In [ ]:
Shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(Shipments)
print("Apples shipped on wednesday",Shipments[0][2])
print("Oranges on sunday ",Shipments[1][6])
weekday=Shipments[:,0:5]
print("Weekday ",weekday)
weekend=Shipments[:,5:7]
print("Weekend ",weekend)
apples=Shipments[0,2:6]
print("Apples from wed to sat ",apples)
Shipments[0, 5] = 100
print(Shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
Apples shipped on wednesday 55
Oranges on sunday  75
Weekday  [[50 60 55 70 65]
 [40 45 50 60 55]]
Weekend  [[80 90]
 [70 75]]
Apples from wed to sat  [55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


Array Operations


In [ ]:
a=np.array([3,4,5])
b=np.array([3,4,5])
print(a+b)
print(a*b)
print(a*2)

[ 6  8 10]
[ 9 16 25]
[ 6  8 10]


In [ ]:
a1=np.array([[2,3,4],[4,5,6]])
b1=np.array([[4,3,1],[7,8,9],[6,7,8]])
res=np.dot(a1,b1)
print(res)

[[53 58 61]
 [87 94 97]]


Broadcasting

In [ ]:
a=np.array([4,5,6])
b=5
print(a+b)
print(np.exp(a))
print(np.sqrt(a))
print(np.min(a))
x=4.56789
print(np.round(x))

[ 9 10 11]
[ 54.59815003 148.4131591  403.42879349]
[2.         2.23606798 2.44948974]
4
5.0


Data Engineer

In [2]:
import numpy as np

# -------------------------------
# 1. Create farm arrays
# -------------------------------
farmA = np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB = np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC = np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])

# Convert to float to allow decimal operations
production_all = np.array([farmA, farmB, farmC], dtype=float)

# -------------------------------
# 2. Array attributes
# -------------------------------
print("Production array:\n", production_all)
print("Shape ", production_all.shape)
print("Size ", production_all.size)
print("Data type ", production_all.dtype)
print("Dimension ", production_all.ndim)

# -------------------------------
# 3. Per-farm totals & stats
# -------------------------------
total_farm = production_all.sum(axis=(1,2))
mean_farm = production_all.mean(axis=(1,2))
std_farm = production_all.std(axis=(1,2))
var_farm = production_all.var(axis=(1,2))
print("Total per farm:", total_farm)
print("Mean per farm:", mean_farm)
print("Std per farm:", std_farm)
print("Var per farm:", var_farm)

# -------------------------------
# 4. Weighted per-panel energy
# -------------------------------
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("Weighted per panel:\n", weighted_per_panel)

# -------------------------------
# 5. Calibration offset for Farm B
# -------------------------------
production_all[1] += 0.5
print("After calibration offset Farm B:\n", production_all[1])

# -------------------------------
# 6. Z-score normalization per farm
# -------------------------------
mean_farm_keep = production_all.mean(axis=(1,2), keepdims=True)
std_farm_keep = production_all.std(axis=(1,2), keepdims=True)
normalized = (production_all - mean_farm_keep) / std_farm_keep
print("Normalized Farm A:\n", normalized[0])

# -------------------------------
# 7. Element-wise ufuncs
# -------------------------------
# Exponential family
exp_vals = np.exp(normalized)
expm1_vals = np.expm1(normalized)
log_vals = np.log(exp_vals)
log10_vals = np.log10(exp_vals)
log2_vals = np.log2(exp_vals)

# Trigonometric
sin_vals = np.sin(normalized)
cos_vals = np.cos(normalized)
tan_vals = np.tan(normalized)
arcsin_vals = np.arcsin(np.clip(normalized/np.max(np.abs(normalized)), -1,1))  # avoid invalid
arccos_vals = np.arccos(np.clip(normalized/np.max(np.abs(normalized)), -1,1))
arctan_vals = np.arctan(normalized)
degrees_vals = np.degrees(arctan_vals)
radians_vals = np.radians(degrees_vals)

# Rounding
rounded_vals = np.round(normalized)
floored_vals = np.floor(normalized)
ceiled_vals = np.ceil(normalized)
truncated_vals = np.trunc(normalized)

# Comparison & logical
high_output = production_all > 20
even_hours_mask = (np.arange(3) % 2 == 0).reshape(1,1,3)
logical_and_mask = np.logical_and(high_output, even_hours_mask)
logical_or_mask = np.logical_or(high_output, even_hours_mask)
logical_not_mask = np.logical_not(high_output)
logical_xor_mask = np.logical_xor(high_output, even_hours_mask)

# Bitwise ufuncs
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],  # Farm A
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],  # Farm B
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]   # Farm C
], dtype=int)
bitwise_and_vals = np.bitwise_and(alerts, 1)
bitwise_or_vals = np.bitwise_or(alerts, 1)
bitwise_invert_vals = np.bitwise_not(alerts)

# Arithmetic ufuncs
added_vals = normalized + 1
subtracted_vals = normalized - 1
multiplied_vals = normalized * 2
divided_vals = normalized / 2
powered_vals = np.power(normalized, 2)
mod_vals = np.mod(normalized, 2)

# Aggregations over ufunc outputs
sum_exp = np.sum(exp_vals)
mean_sin = np.mean(sin_vals)
print("Sum of exp(normalized):", sum_exp)
print("Mean of sin(normalized):", mean_sin)

# -------------------------------
# 8. Panel totals & maintenance check
# -------------------------------
panel_totals_per_farm = production_all.sum(axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)

# -------------------------------
# 9. Final KPIs
# -------------------------------
overall_total = production_all.sum()
peak_hour_value = production_all.max()
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = production_all.mean(axis=2)
print("Overall total energy:", overall_total)
print("Peak hour value:", peak_hour_value)
print("Peak produced by farm/panel:", peak_idx)
print("Average per panel:\n", average_per_panel)


Production array:
 [[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[20. 19. 21.]
  [18. 20. 19.]
  [22. 23. 21.]
  [17. 18. 16.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]
Shape  (3, 4, 3)
Size  36
Data type  float64
Dimension  3
Total per farm: [126. 234. 174.]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Var per farm: [3.91666667 3.91666667 3.91666667]
Weighted per panel:
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
After calibration offset Farm B:
 [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]
Normalized Farm A:
 [[-0.25264558  0.75793673  0.25264558]
 [-0.75793673  0.25264558 -0.25264558]
 [ 0.75793673  1.26322788  1.76851903]
 [-1.26322788 -1.76851903 -0.75793673]]
Sum of exp(normalized): 57.55695815214101
Mean of sin(normalized): 6.1679056923619804e-18
Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.

In [ ]:
arr=np.array([12,1,45,2,56,9])
ree=arr.reshape(3,2)
print(ree)

[[12  1]
 [45  2]
 [56  9]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr=np.array([12,23,34,45])
print(np.array_split(arr,2))

[array([12, 23]), array([34, 45])]


In [ ]:
a=np.array([1,2,3,4,5])
print(a[a>2])

[3 4 5]


In [ ]:
a=np.array([2,3,4,5])
view=a.view()
view[0]=10
print(a)
c=a.copy()
c[1]=2
print(a)

[10  3  4  5]
[10  3  4  5]


In [ ]:
a=np.array([1,2,3])
np.save('array.npy',a)
load=np.load('array.npy')
print(load)

[1 2 3]


#TaskArray Creation

In [ ]:
array=np.arange(10,51)
print(array)
x=np.random.rand(3,3)
print(x)
print(x.shape)
print(x.size)
print(x.dtype)
b=5
print(array+5)
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[7,8,9],[10,11,12]])
res=m1*m2
print(res)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.1617874  0.41911382 0.40295911]
 [0.20121508 0.9946938  0.02350692]
 [0.49033316 0.90887926 0.25598845]]
(3, 3)
9
float64
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 7 16 27]
 [40 55 72]]


In [ ]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
print(arr[0])
print(arr[:,-1])
print(arr[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
arr=np.random.randint(10,101,size=10)
print(arr)
print("Max value ",arr.max())
print("Min vaue ",arr.min())
print("Mean ",arr.mean())
print("Standard deviation ",arr.std())

[66 43 47 82 89 43 70 48 87 91]
Max value  91
Min vaue  43
Mean  66.6
Standard deviation  18.99052395275075


In [ ]:
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ones=np.ones((3,3))
print(ones)
print(ones+[1,2,3])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
a=np.random.randint(1,51,size=20)
print(a[a%5==0])


[15 25 30 15]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3],[4,5],[5,6]])
print(np.dot(a,b))

[[25 31]
 [58 73]]


In [ ]:
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
diagonal = arr[np.arange(4), np.arange(4)]
print("Diagonal elements:", diagonal)

Diagonal elements: [ 1  6 11 16]
